<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Customer;
use Illuminate\Support\Facades\DB;

class CustomerSeeder extends Seeder
{
    public function run()
    {
        $customers = [
            [
                'number' => '588',
                'name' => '陳映伶',
                'email' => null,
                'id_number' => 'A225543069',
                'birthday' => '1991-05-18',
                'address' => '新北市永和區永和路378號23樓之2',
                'phone' => '0910222275',
                'company_name' => '映伶服裝設計工作室有限公司',
                'company_number' => '82823566',
                'company_website' => null,
                'company_email' => null,
                'company_address' => '新北市永和區永和路378號23樓之2',
                'company_phone_number' => '0910222275',
                'company_fax_number' => null,
                'company_contact_person' => '陳映伶',
                'company_contact_person_phone_number' => '0910222275',
                'company_contact_person_email' => null,
                'line_id' => '映伶 Ying',
                'line_nickname' => '映伶 Ying',
                'id_card_front' => null,
                'id_card_back' => null,
                'remark' => null,
                'status' => 1,
                'modify' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'branch_id' => 1,
                'branch_name' => '台北信義安和館',
            ],
            [
                'number' => '589',
                'name' => '黃麗珠',
                'email' => null,
                'id_number' => null,
                'birthday' => null,
                'address' => '台北市南港區向陽路204-13號一樓',
                'phone' => '0910020457',
                'company_name' => '威視科技有限公司',
                'company_number' => '55821585',
                'company_website' => null,
                'company_email' => null,
                'company_address' => '台北市南港區向陽路204-13號一樓',
                'company_phone_number' => '0910020457',
                'company_fax_number' => null,
                'company_contact_person' => '黃麗珠',
                'company_contact_person_phone_number' => '0910020457',
                'company_contact_person_email' => null,
                'line_id' => 'L.Y. ViviAn',
                'line_nickname' => 'L.Y. ViviAn',
                'id_card_front' => null,
                'id_card_back' => null,
                'remark' => null,
                'status' => 1,
                'modify' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'branch_id' => 2,
                'branch_name' => '台中館大忠館',
            ],
            [
                'number' => '590',
                'name' => '林怡君',
                'email' => null,
                'id_number' => null,
                'birthday' => null,
                'address' => '台北市南港區向陽路204-13號一樓',
                'phone' => '0910020457',
                'company_name' => '威視科技有限公司',
                'company_number' => '55821585',
                'company_website' => null,
                'company_email' => null,
                'company_address' => '台北市南港區向陽路204-13號一樓',
                'company_phone_number' => '0910020457',
                'company_fax_number' => null,
                'company_contact_person' => '黃麗珠',
                'company_contact_person_phone_number' => '0910020457',
                'company_contact_person_email' => null,
                'line_id' => 'L.Y. ViviAn',
                'line_nickname' => 'L.Y. ViviAn',
                'id_card_front' => null,
                'id_card_back' => null,
                'remark' => null,
                'status' => 1,
                'modify' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'branch_id' => 3,
                'branch_name' => '台南東寧館',
            ],
            [
                'number' => '591',
                'name' => '李怡君',
                'email' => null,
                'id_number' => null,
                'birthday' => null,
                'address' => '台北市南港區向陽路204-13號一樓',
                'phone' => '0910020457',
                'company_name' => '威視科技有限公司',
                'company_number' => '55821585',
                'company_website' => null,
                'company_email' => null,
                'company_address' => '台北市南港區向陽路204-13號一樓',
                'company_phone_number' => '0910020457',
                'company_fax_number' => null,
                'company_contact_person' => '黃麗珠',
                'company_contact_person_phone_number' => '0910020457',
                'company_contact_person_email' => null,
                'line_id' => 'L.Y. ViviAn',
                'line_nickname' => 'L.Y. ViviAn',
                'id_card_front' => null,
                'id_card_back' => null,
                'remark' => null,
                'status' => 1,
                'modify' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'branch_id' => 4,
                'branch_name' => '台南崇學館',
            ],
            [
                'number' => '592',
                'name' => '王怡君',
                'email' => null,
                'id_number' => null,
                'birthday' => null,
                'address' => '台北市南港區向陽路204-13號一樓',
                'phone' => '0910020457',
                'company_name' => '威視科技有限公司',
                'company_number' => '55821585',
                'company_website' => null,
                'company_email' => null,
                'company_address' => '台北市南港區向陽路204-13號一樓',
                'company_phone_number' => '0910020457',
                'company_fax_number' => null,
                'company_contact_person' => '黃麗珠',
                'company_contact_person_phone_number' => '0910020457',
                'company_contact_person_email' => null,
                'line_id' => 'L.Y. ViviAn',
                'line_nickname' => 'L.Y. ViviAn',
                'id_card_front' => null,
                'id_card_back' => null,
                'remark' => null,
                'status' => 1,
                'modify' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'branch_id' => 5,
                'branch_name' => '台南中山館',
            ],

            // ... 可以繼續添加其他客戶數據
        ];

        foreach ($customers as $customer) {
            Customer::create($customer);
        }
    }
}